// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZuUEEO8_gLbswPoEFtd68sfbREbV2lfk',
    appId: '1:618035919595:web:ddbd56e9f094de106f5cae',
    messagingSenderId: '618035919595',
    projectId: 'flutter-authentication-93518',
    authDomain: 'flutter-authentication-93518.firebaseapp.com',
    storageBucket: 'flutter-authentication-93518.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIpPjqBXQBdc26kySp-9wBGmoo6w0OWX0',
    appId: '1:618035919595:android:ce14a5b6d95fa3a36f5cae',
    messagingSenderId: '618035919595',
    projectId: 'flutter-authentication-93518',
    storageBucket: 'flutter-authentication-93518.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeQ7MErRI8QSkiYjkSYy83aU7nSk8Yp9U',
    appId: '1:618035919595:ios:d4a63b2ec0d1a1096f5cae',
    messagingSenderId: '618035919595',
    projectId: 'flutter-authentication-93518',
    storageBucket: 'flutter-authentication-93518.appspot.com',
    iosClientId: '618035919595-vo45k1b80bgit2r9cddg9jrcgo06vf40.apps.googleusercontent.com',
    iosBundleId: 'com.example.fluttterAuthentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeQ7MErRI8QSkiYjkSYy83aU7nSk8Yp9U',
    appId: '1:618035919595:ios:d4a63b2ec0d1a1096f5cae',
    messagingSenderId: '618035919595',
    projectId: 'flutter-authentication-93518',
    storageBucket: 'flutter-authentication-93518.appspot.com',
    iosClientId: '618035919595-vo45k1b80bgit2r9cddg9jrcgo06vf40.apps.googleusercontent.com',
    iosBundleId: 'com.example.fluttterAuthentication',
  );
}
